# Generated by Django 6.0.3 on 2026-04-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('cards', 'Cards'), ('rings', 'Rings'), ('other', 'Other')], default='cards', max_length=20)),
                ('material_label', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency_code', models.CharField(default='EUR', max_length=3)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('availability_status', models.CharField(choices=[('in_stock', 'In stock'), ('low_stock', 'Low stock'), ('sold_out', 'Sold out'), ('coming_soon', 'Coming soon')], default='in_stock', max_length=20)),
                ('primary_image', models.ImageField(blank=True, upload_to='products/')),
                ('static_asset', models.CharField(blank=True, max_length=255)),
                ('feature_media', models.FileField(blank=True, upload_to='products/feature/')),
                ('static_feature_asset', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='showcase/')),
                ('link_label', models.CharField(default='Create Profile', max_length=80)),
                ('link_url', models.CharField(default='/accounts/signup/', max_length=255)),
                ('theme', models.CharField(choices=[('ink', 'Ink'), ('wood', 'Wood'), ('glass', 'Glass')], default='ink', max_length=12)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
